### ISSUE TITLE
Idea ) 추론관련 아이디어

### ISSUE THREAD

**Issue by popop098** [ORI-Muchim/PolyLangVITS#2]
- 추론할때마다 일일히 코드를 수정하는 과정없이 커맨드 입력할때 맨뒷부분에 대사를 입력함으로서 한번에 생성토록 하는 기능 제의드립니다.
`ex) python inference.py {Model} {Step} {Script | 안녕하세요!}`

- 보이스 체인저에선 사용이 불가함에 따라 SpeechToText를 사용해 보이스 체인저를 모방한 추론기능을 제의드립니다.
`과정) 오디오 입력 --> Whisper로 대사 추출 --> 추출된 대사로 추론 --> 결과음성파일 저장`

**Comment by ORI-Muchim** [comment]
좋은 아이디어 같습니다. 다만, 2번 같은 경우에는 기능을 추가하는데 약간의 시간이 걸릴 수 있다는 것을 미리 알려드립니다.

**Comment by popop098** [comment]
괜찮습니다 천천히 추가해주세요! 미리 감사드립니다!

**Comment by kdrkdrkdr** [comment]
@popop098 
좋은 의견 감사드리지만, 애초에 해당 모델은 Voice Conversion 모델이 아닙니다.  2번 항목은 [RVC](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI) 나, [so-vits-svc](https://github.com/voicepaw/so-vits-svc-fork) 를 참고하시기 바랍니다:)
