### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '../datasets/vits_train.txt.cleaned'

### ISSUE THREAD

**Issue by zhanglina94** [ORI-Muchim/PolyLangVITS#4]
안녕하세요~
제가 run `python main.py KO vits 22050`할 때
이런 오류가 있습니다
![image](https://github.com/ORI-Muchim/PolyLangVITS/assets/43246784/171aee92-9e88-43e4-8e19-be4613db3f60)

그래서 수정했는데요
![image](https://github.com/ORI-Muchim/PolyLangVITS/assets/43246784/e5364e0e-033e-4538-a9cf-e3930d03df5e)
그래도 오류가 나타났습니다~
![image](https://github.com/ORI-Muchim/PolyLangVITS/assets/43246784/3c7cfc9b-7bf6-4be1-8c64-d6d2d4a27cd6)
죄송하지만 혹시 왜 오류가 나는지 알 수 있을까요?

**Comment by ORI-Muchim** [comment]
안녕하세요! ./datasets/integral.py 파일 안에 사용법이 있습니다. 주석처리 해놓으신 부분 원래대로 수정해주시고, `python main.py KO vits 22050` 이 명령어에서 `KO`를 소문자 `ko`로 쓰시면 해결될겁니다.

**Comment by ORI-Muchim** [comment]
또한, 마지막에서 보이는 오류는 `sample_rate`가 맞지 않아 생기는 문제입니다. 데이터셋의 샘플레이트를 확인해주세요.

**Comment by zhanglina94** [comment]
넵넵,알겠습니다,해보겠습니다,감사합니다~~
